### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by niloofartrg**
Are these Json files enough or should I dedicate one file to each change? @monperrus

### CODE REVIEW

**Comment by monperrus** [comment]
that's a great first start. Those files do not contain the diffs. How to add them? In the JSON or as separate files?

**Comment by niloofartrg** [comment]
I added such output to the JSON file. Is that right?


"diff": "[ChangePatternInstance [actions\u003d[Delete Invocation at org.apache.commons.lang3.builder.ToStringBuilderTest:320\n\tassumeFalse(((\"IBM Corporation\".equals(org.apache.commons.lang3.SystemUtils.JAVA_VENDOR)) \u0026\u0026 (\"1.6\".equals(org.apache.commons.lang3.SystemUtils.JAVA_SPECIFICATION_VERSION))))\n]]
, 

ChangePatternInstance [actions\u003d[Delete Invocation at org.apache.commons.lang3.builder.ToStringBuilderTest:320\n\tassumeFalse(((\"IBM Corporation\".equals(org.apache.commons.lang3.SystemUtils.JAVA_VENDOR)) \u0026\u0026 (\"1.6\".equals(org.apache.commons.lang3.SystemUtils.JAVA_SPECIFICATION_VERSION))))\n]]]"

**Comment by monperrus** [comment]
this is hard to read,

ideally we would have one file project/<revision>.diff with the labels at the top (easy to read plus
free syntax highlighting by Github)

**Comment by niloofartrg** [comment]
but what I added is the diff?

So if I break this Json file into multiple files, each file for one revision and the name of the tools detected at each revision at the top it would be right?

**Pull request merged**
